### ISSUE TITLE
gaps between the metrics

### ISSUE THREAD

**Issue by bobykus31** [ricoberger/script_exporter#104]
Since we started using script_exporter, we found a weird issue that makes us uncomfortable. We use script_exporter to execute some long-running scripts like smartctl metrics. Even though we have a reasonable cache duration set up, we still have gaps in between the metrics, that correspond to the time of script execution or close. The script-exporter.yml looks like 

```
scripts:
...
- name: node_smartmon
  command: "/usr/lib/prometheus/custom_metric_node_smartmon.sh"
  cacheDuration: 1200s
  timeout:
    max_timeout: 600
    enforced: false
```
The result is 

![image](https://github.com/ricoberger/script_exporter/assets/38345247/f2300c80-dbee-4bc7-941f-0bdc7144edae)

Is there any good way to get rid of this gaps?
