### ISSUE TITLE
Example script that always fails and will set job in Prometheus in down status

### ISSUE THREAD

**Issue by wegerv** [ricoberger/script_exporter#129]
From issue 21 I understand that failing scripts can trigger a down status in Prometheus. I'm struggling how to do that though. 

Should I use an exit code (and if so 5xx or 1?), should I echo a value for a 'up' metric, should I echo a value for script_exporter_exit_code or script_exporter_up? 

Would it be possible to add a script in the examples that always fails in the way that Prometheus picks up the result?

Thanks in advance.

**Comment by ricoberger** [comment]
Hi @wegerv, I'm not sure if I get it correctly, but what you can do is to create a script as follows:

```sh
#!/bin/bash

sleep 30
exit 1
```

And then define a scrape config with a `scrape_timeout` below the sleep time:

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: script_should_fail
    metrics_path: /probe
    params:
      script: [ping]
    static_configs:
      - targets:
        - 127.0.0.1:9469
```

With this Prometheus should always report it as down:

<img width="1783" alt="Bildschirmfoto 2024-04-26 um 22 26 28" src="https://github.com/ricoberger/script_exporter/assets/18552168/8b3c59f1-74a4-4c5d-9973-ac8224e109cb">

**Comment by wegerv** [comment]
Thanks for the example. The strange thing is that it doesn't work like that in Prometheus.

A probe on the script results an error state -- as expected --:

# HELP script_success Script exit status (0 = error, 1 = success).
# TYPE script_success gauge
script_success{script="fail"} 0
# HELP script_duration_seconds Script execution time, in seconds.
# TYPE script_duration_seconds gauge
script_duration_seconds{script="fail"} 0.051637
# HELP script_exit_code The exit code of the script.
# TYPE script_exit_code gauge
script_exit_code{script="fail"} 1

However, Prometheus reports an 'UP' status. I think the status in your example is down because the scrape_timeout is shorter than the sleep time in the script example.

I'm using version 2.50.1 on windows of Prometheus.

**Comment by wegerv** [comment]
I've been looking into this. Script_exporter logs an error:

```
C:\bin\prometheus\script_exporter-2.18.0>script_exporter-windows-amd64.exe --log.level=debug
ts=2024-04-28T12:19:27.792Z caller=exporter.go:136 level=info msg="Starting script_exporter" version="(version=v2.18.0, branch=HEAD, revision=ebeaf9415eb13c14dab809cfbe8ff06e7465b0bd)"
ts=2024-04-28T12:19:27.792Z caller=exporter.go:137 level=info msg="Build context" build_context="(go=go1.21.6, user=runner, date=20240210-12:39:39)"
ts=2024-04-28T12:19:27.793Z caller=exporter.go:138 level=info msg="Listening on :9469"
ts=2024-04-28T12:20:26.310Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"
ts=2024-04-28T12:21:26.328Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"
ts=2024-04-28T12:22:26.346Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"
ts=2024-04-28T12:23:26.329Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"
ts=2024-04-28T12:24:26.318Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"
ts=2024-04-28T12:25:26.445Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"
ts=2024-04-28T12:26:26.306Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"
ts=2024-04-28T12:27:26.324Z caller=scripts.go:93 level=error msg="Script 'fail' execution failed" cmd=C:\bin\prometheus\script_exporter-2.18.0\scripts\fail.cmd stdout="\r\nC:\\bin\\prometheus\\script_exporter-2.18.0>exit 1 \r\n" stderr= env= err="exit status 1"

The fail.cmd script only contains 

`exit 1
`

What am I doing wrong here?

```

**Comment by ricoberger** [comment]
Hi @wegerv, yes it is just reporting DOWN because of the timeout.

I think it is not possible to mark the target as DOWN based on the returned metric, since the state is only used by Prometheus if there is a problem with scraping the metrics.

**Comment by ricoberger** [comment]
Yes correct this is not possible.

What you can still do is to use the following metrics:

- `up == 0`: Monitor the DOWN status, if Prometheus has a problem to scrape the metrics of the exporter
- `script_success == 0`: Monitor if the script failed

**Comment by wegerv** [comment]
Sorry, you lost me. Do I configure that in the rules in Prometheus?

Something like this:
```
groups:
- name: fail_script.rules
  rules:
  - alert: FailScriptDown
    expr: up{job="fail"} == 0
    for: 3m
```

**Comment by ricoberger** [comment]
Yes, for example you can have the following rules:

```
groups:
- name: script_exporter
  rules:
  - alert: TargetDown
    expr: up{job="script-exporter"} == 0
    for: 3m
    annotations:
      summary: script_exporter target could not be scraped by Prometheus
  - alert: ScriptFailure
    expr: script_success{job="script-exporter"} == 0
    for: 3m
    annotations:
      summary: Script execution failed
```

If you are using Alertmanager you can then get an alert when the script_exporter metrics couldn't be scraped by Prometheus or when the execution of a script failed.
