### ISSUE TITLE
allow probe?name=x instead of probe?script=x

### ISSUE THREAD

**Issue by milahu** [ricoberger/script_exporter#156]
make it backward-compatible with [version 1](https://github.com/adhocteam/script_exporter)
or document this as a [breaking change](https://github.com/ricoberger/script_exporter#breaking-changes)

currently it says

```
$ curl -s http://localhost:9004/probe?name=x
Script parameter is missing
```

`name=x` also aligns with the config

```yaml
scripts:
  - name: <string>
    command: <string>
```
