### ISSUE TITLE
about executing docker scripts

### ISSUE THREAD

**Issue by xhuan-wang** [ricoberger/script_exporter#26]
Hi , i'm using your script_exporter . its great !!! However , when i executed a shell script about docker  with your script_exporter, it returned an error result , but it return the correct result when i executed the script through ```sh script.sh``` ,  i can't see the log and I don't know why , 
```yml
#!/bin/sh
source /etc/profile
result="$(sudo docker exec -it mysql_slave1 mysql -utest -p'test'  -e "show slave status\G" |grep "Slave_IO_Running: Yes"|wc -l)"
echo "# HELP mysql_slave1_io_running"
echo "# TYPE mysql_slave1_io_running gauge"
echo "mysql_slave1_io_running{label=\"mysql_slave1_io_running\"} $result"
```
```yml
tls:
  enabled: false
  crt: server.crt
  key: server.key

basicAuth:
  enabled: false
  username: admin
  password: admin

bearerAuth:
  enabled: false
  signingKey: my_secret_key

scripts:
  - name: mysql_slave1_sql_running
    script: ./test.sh
    timeout:
      max_timeout: 60
  - name: sleep
    script: sleep 120
    timeout:
      enforced: true
```

Can you help me?
