### ISSUE TITLE
expected label value, got "INVALID"

### ISSUE THREAD

**Issue by rudhra13** [ricoberger/script_exporter#27]
hi,

I am trying script exporter, I am able to make it work, and it is outputting the expected values using curl request.
`curl "http://server.stag.use1b.com:9469/probe?script=check_service_script"`

but when I am trying to scrape using Prometheus, I am getting `expected label value, got "INVALID"` error in Prometheus.
Prometheus config:
```
  - job_name: 'script_check'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      script: ['check_service_script']
    static_configs:
    - targets: ['server.stag.use1b.com:9469']
```

can you tell me what could be the issue here?

script exporter version
[root@server examples]# script_exporter-linux-amd64 --version
script_exporter, version v2.2.0 (branch: HEAD, revision: b698e33ad6c7d5f32c43de163e7ef43f970c9c1d)
  build user:       runner
  build date:       20200508-06:03:16
  go version:       go1.13.10
