### ISSUE TITLE
Get script exit code as a metric

### ISSUE THREAD

**Issue by acdmail** [ricoberger/script_exporter#34]
hi,
Could you advise please if there is a way in the current release to get as a metric returned, script original exit code?

Thanks in advance

**Comment by ricoberger** [comment]
Hi @acdmail, the exit code is currently not collected. We only have the `script_success` metric, which is `0` when the exit code of the script was 0 and `1` when the exit code of the script was not 0.

If you want the exit code of the script as metric, we might be able to create this metric by checking [here](https://github.com/ricoberger/script_exporter/blob/304d8e60eff8c43cacf54f479eed340237e7e3a6/cmd/script_exporter/script_exporter.go#L107) if we can get the exit code with sth. like:

```go
if exitError, ok := err.(*exec.ExitError); ok {
    return "", exitError.ExitCode(), err
}
```

Is this sth. you are interested in, then I can take a look at this during the next days?

**Comment by acdmail** [comment]
@ricoberger Yes this is exactly the feature which I would appreciate to be added. This should allow reuse of some already existing scripts without the wrapper script but for this it would be also nice to have the ability to suppress the script output. So in case that there are some existing script which is returning the exit code but also the output not in the Prometheus metric for it to be surpressed.
Thank you

**Comment by ricoberger** [comment]
Hi @acdmail, I added support for the exit code in #36, where a new metric named `script_exporter_exit_code` is created. Can you please test one of the build from https://github.com/ricoberger/script_exporter/actions/runs/1234271213. If this looks ok for you I would merge the PR and create a new release.

You can already ignore the output of a script by adding the `output=ignore` ignore parameter to the scrape configuration:

```
scrape_configs:
  - job_name: 'script_ping'
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      script: [ping]
      prefix: [script_ping]
      params: [target]
      output: [ignore]
    static_configs:
      - targets:
        - example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9469
      - source_labels: [__param_target]
        target_label: target
      - source_labels: [__param_target]
        target_label: instance
```
