### ISSUE TITLE
Define script parameters in config as array

### ISSUE THREAD

**Issue by Nick-Triller** [ricoberger/script_exporter#55]
Hi there!

Currently, the `script` string is split on spaces to generate the program name and any fixed arguments. This approach means that the [program name](https://github.com/ricoberger/script_exporter/issues/51) and fixed arguments can't contain spaces.

I propose that fixed arguments in the exporter config should be defined as an array instead of being defined in the `script` property, e.g. something like this:

Example 1:
```yaml
scripts:
  - name: "example1"
    command: "./examples/connectivity-check.sh"
    args:
    - "google.com"
    - "bing.com"
```

Example 2:
```yaml
scripts:
  - name: "example2"
    command: "netcat"
    args:
    - "-vzw"
    - "2"
    - "example.com"
```

The change can be implemented in a backwards compatible way:
1. Keep `script` property with current behaviour.
2. Require either `script` or `command` to be defined.
3. Error if `script` is combined with `args` or `command`. `args` is always optional.

This is also how arguments are passed to a process in a Kubernetes pod manifest which means it will feel natural to many users of script_exporter:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
spec:
  containers:
  - name: command-demo-container
    image: debian
    command:
    - "printenv"
    args:
    - "HOSTNAME"
    - "KUBERNETES_PORT"
```

 @ricoberger let me know what you think, I will be happy to implement this change.
