### ISSUE TITLE
Call does not wait for script execution to finish

### ISSUE THREAD

**Issue by DgoNascimento** [ricoberger/script_exporter#57]
Hello guys,

I would like some help.

I'm using script_exporter to run a shell script, which runs another powershell script.

Executing the shell script, I have the return successfully, even though the return is not immediate, taking 30s for example.

Even though I configure the scrap time and the timeout time, whenever I execute the curl call from the exporter, the return is immediate and with that it does not return the echo (variable created with the expected value).

Would you have any idea why?

Would it be because of the shell script to run another power shell?

Thank you very much!

**Comment by DgoNascimento** [comment]
@ricoberger could you support?

**Comment by ricoberger** [comment]
HI @DgoNascimento, I'm not quite sure what the problem could be. Maybe you can use the following two examples to test if this is timeout related:

```yaml
scripts:
  - name: showtimeout
    script: sh /bin/examples/showtimeout.sh
    timeout:
      max_timeout: 60
  - name: sleep
    script: sleep 120
    timeout:
      enforced: true
```

It is also possible that the script doesn't wait for the execution of your other powershell script. Maybe sth. in this direction could help here: https://stackoverflow.com/questions/1741490/how-to-tell-powershell-to-wait-for-each-command-to-end-before-starting-the-next
