### ISSUE TITLE
env: expects list of strings, not a map.

### ISSUE THREAD

**Issue by gacerioni** [ricoberger/script_exporter#80]
**Howdy, Rico!**

I have a sensitive pwd that I'd like to provide via env vars.

I tried to follow this snippet as an example:

```
scripts:
  - name: test_env
    command: /tmp/my_script.sh
    env:
      http_proxy: http://proxy.example.com:3128
      https_proxy: http://proxy.example.com:3128
```

But it throws this message:

`script_exporter[2622]: ts=2023-07-03T22:48:51.713Z caller=exporter.go:57 level=error err="yaml: unmarshal errors:\n  line 5: cannot unmarshal !!map into []string"
`

**Version:** [v2.12.0](https://github.com/ricoberger/script_exporter/releases/tag/v2.12.0)

**Long shoot:**
And when I provide the env var as a list of str, it works:

```
scripts:
  - name: test_env
    command: /tmp/my_script.sh
    env:
    - http_proxy
    - https_proxy
```
